/**
 * Rita Go Search Component
 * Based on CustomSearch but adapted for Rita Go with blue-black theme and badge filtering
 */

import React, { useState, useRef, useEffect, useCallback } from 'react'
import { useHistory, useLocation } from '@docusaurus/router'
import {
  Paper,
  List,
  ListItem,
  ListItemButton,
  Typography,
  Box,
  Chip,
  CircularProgress,
  Divider,
  Button,
  ButtonGroup,
} from '@mui/material'
import styles from './styles.module.css'

// Import Rita Go mappings (will be generated by scanner)
let ritaGoLatest = {}
try {
  ritaGoLatest = require('@site/static/data/enhanced-title-mappings-rita-go-latest.json')
} catch (error) {
  console.warn('Rita Go mappings not found - run npm run scan-rita-go')
}

const ALL_MAPPINGS = {
  'rita-go-latest': ritaGoLatest,
}

// Rita Go theme colors - blue-black with matching badge colors
const getRitaGoTheme = () => ({
  primary: 'var(--brand-blue)', // Blue from badge system
  secondary: 'var(--brand-aqua)', // Aqua from badge system
  outline: '#1a202c', // Blue-black outline
  background: 'var(--brand-white)',
  text: 'var(--brand-black)',
  selection: 'var(--brand-grey-200)',
})

// Badge color functions matching FeatureBadges component
const getBadgeColor = badgeType => {
  switch (badgeType) {
    case 'users':
      return 'var(--brand-blue)'
    case 'admin':
      return 'var(--brand-aqua)'
    case 'both':
      return 'linear-gradient(135deg, var(--brand-blue) 0%, var(--brand-aqua) 100%)'
    default:
      return 'var(--brand-grey-500)'
  }
}

// Debounce utility
const debounce = (func, wait) => {
  let timeout
  return function executedFunction(...args) {
    const later = () => {
      clearTimeout(timeout)
      func(...args)
    }
    clearTimeout(timeout)
    timeout = setTimeout(later, wait)
  }
}

const RitaGoSearch = () => {
  const [query, setQuery] = useState('')
  const [results, setResults] = useState([])
  const [isOpen, setIsOpen] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [selectedIndex, setSelectedIndex] = useState(-1)
  const [adminFilter, setAdminFilter] = useState(false) // Admin checkbox state
  const [usersFilter, setUsersFilter] = useState(false) // Users checkbox state

  const searchRef = useRef(null)
  const dropdownRef = useRef(null)
  const inputRef = useRef(null)
  const history = useHistory()
  const location = useLocation()
  const theme = getRitaGoTheme()

  // Search function for Rita Go
  const performRitaGoSearch = useCallback(
    searchQuery => {
      if (!searchQuery.trim()) {
        setResults([])
        setIsLoading(false)
        return
      }

      try {
        console.log('🔍 Rita Go Search:', searchQuery)

        const mappings = ritaGoLatest || {}
        const entries = Object.entries(mappings).filter(
          ([key, value]) =>
            key && typeof key === 'string' && !key.startsWith('_') && value,
        )

        if (entries.length === 0) {
          console.warn('No Rita Go mappings available')
          setResults([])
          setIsLoading(false)
          return
        }

        const queryLower = searchQuery.toLowerCase()
        const searchTerms = queryLower
          .split(/\s+/)
          .filter(term => term.length > 0)

        const allResults = entries
          .map(([title, data]) => {
            try {
              const titleLower = title.toLowerCase()
              const excerptLower = (data.excerpt || '').toLowerCase()
              const headersText = (data.headers || []).join(' ').toLowerCase()
              const searchTermsText = (data.contentType?.searchTerms || [])
                .join(' ')
                .toLowerCase()

              // Calculate relevance score
              let score = 0

              // Title exact match (highest priority)
              if (titleLower.includes(queryLower)) {
                score += 100
              }

              // Title word matches
              searchTerms.forEach(term => {
                if (titleLower.includes(term)) {
                  score += 50
                }
              })

              // Header matches
              searchTerms.forEach(term => {
                if (headersText.includes(term)) {
                  score += 30
                }
              })

              // Excerpt matches
              searchTerms.forEach(term => {
                if (excerptLower.includes(term)) {
                  score += 20
                }
              })

              // Search terms matches
              searchTerms.forEach(term => {
                if (searchTermsText.includes(term)) {
                  score += 15
                }
              })

              if (score === 0) return null

              // Apply badge filtering based on checkbox states
              const badgeType = data.badgeType || 'none'

              // If neither filter is checked, show all results
              if (!adminFilter && !usersFilter) {
                // Show all results
              }
              // If only admin filter is checked
              else if (adminFilter && !usersFilter) {
                if (badgeType !== 'admin' && badgeType !== 'both') {
                  return null
                }
              }
              // If only users filter is checked
              else if (!adminFilter && usersFilter) {
                if (badgeType !== 'users' && badgeType !== 'both') {
                  return null
                }
              }
              // If both filters are checked, show all results (no filtering needed)
              else if (adminFilter && usersFilter) {
                // Show all results
              }

              return {
                title,
                url: data.url || '',
                breadcrumbs: `Rita Go > ${
                  data.contentType?.category || 'Documentation'
                }`,
                contentType: {
                  type: data.contentType?.type || 'reference',
                  subtype: data.contentType?.subtype || '',
                  category: data.contentType?.category || 'documentation',
                },
                complexity: data.complexity || 'simple',
                excerpt: data.excerpt || '',
                score,
                badgeType,
                isRitaGo: true,
                data,
              }
            } catch (error) {
              console.error('Error processing Rita Go result:', title, error)
              return null
            }
          })
          .filter(Boolean)

        // Sort by score and limit results
        const finalResults = allResults
          .sort((a, b) => b.score - a.score)
          .slice(0, 8)

        console.log('🔍 Rita Go SEARCH RESULTS:')
        finalResults.forEach((result, i) => {
          console.log(`  ${i + 1}. ${result.title} [${result.badgeType}]`)
        })

        setResults(finalResults)
        setIsLoading(false)
      } catch (error) {
        console.error('Rita Go search error:', error)
        setResults([])
        setIsLoading(false)
      }
    },
    [adminFilter, usersFilter],
  )

  // Debounced search function
  const debouncedSearch = useCallback(
    debounce(searchQuery => {
      performRitaGoSearch(searchQuery)
    }, 300),
    [performRitaGoSearch],
  )

  // Handle search input changes
  const handleInputChange = e => {
    const value = e.target.value
    setQuery(value)
    setSelectedIndex(-1)

    if (value.trim()) {
      setIsLoading(true)
      setIsOpen(true)
      debouncedSearch(value)
    } else {
      setResults([])
      setIsOpen(false)
      setIsLoading(false)
    }
  }

  // Handle keyboard navigation
  const handleKeyDown = e => {
    if (!isOpen || results.length === 0) {
      if (e.key === 'Escape') {
        setIsOpen(false)
        inputRef.current?.blur()
      }
      return
    }

    const totalItems = results.length

    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault()
        setSelectedIndex(prev => (prev < totalItems - 1 ? prev + 1 : prev))
        break

      case 'ArrowUp':
        e.preventDefault()
        setSelectedIndex(prev => (prev > 0 ? prev - 1 : -1))
        break

      case 'Enter':
        e.preventDefault()
        if (selectedIndex >= 0 && results[selectedIndex]) {
          navigateToResult(results[selectedIndex])
        }
        break

      case 'Escape':
        e.preventDefault()
        setIsOpen(false)
        inputRef.current?.blur()
        break
    }
  }

  // Navigate to selected result
  const navigateToResult = result => {
    history.push(result.url)
    setQuery('')
    setResults([])
    setIsOpen(false)
    inputRef.current?.blur()
  }

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = event => {
      if (searchRef.current && !searchRef.current.contains(event.target)) {
        setIsOpen(false)
      }
    }

    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  // Re-search when filter changes
  useEffect(() => {
    if (query.trim() && isOpen) {
      setIsLoading(true)
      performRitaGoSearch(query)
    }
  }, [adminFilter, usersFilter])

  return (
    <div className={styles.ritaGoSearchContainer}>
      {/* Search Input */}
      <div ref={searchRef} className={styles.searchInputContainer}>
        <input
          ref={inputRef}
          type='text'
          placeholder='Search Rita Go...'
          value={query}
          onChange={handleInputChange}
          onKeyDown={handleKeyDown}
          onFocus={e => {
            if (query) setIsOpen(true)
            e.target.style.borderColor = 'var(--brand-black)'
            e.target.style.boxShadow = `0 0 0 2px rgba(0, 80, 199, 0.2)`
          }}
          onBlur={e => {
            setTimeout(() => {
              if (!dropdownRef.current?.contains(document.activeElement)) {
                e.target.style.borderColor = 'var(--brand-grey-600)'
                e.target.style.boxShadow = 'none'
              }
            }, 150)
          }}
          className={styles.searchInput}
          aria-label='Search Rita Go documentation'
          aria-expanded={isOpen}
          aria-autocomplete='list'
        />

        {/* Search Results Dropdown */}
        {isOpen && (
          <Paper
            ref={dropdownRef}
            className={styles.searchDropdown}
            sx={{
              border: `2px solid var(--brand-black)`,
              backgroundColor: theme.background,
              display: 'flex',
              flexDirection: 'column',
              height: '400px', // Fixed height
            }}
          >
            {isLoading ? (
              <Box className={styles.loadingContainer}>
                <CircularProgress size={20} sx={{ color: theme.primary }} />
                <Typography variant='body2' sx={{ color: theme.text }}>
                  Searching Rita Go...
                </Typography>
              </Box>
            ) : results.length > 0 ? (
              <>
                {/* Scrollable Results Area */}
                <Box className={styles.resultsContainer}>
                  <List className={styles.resultsList}>
                    {results.map((result, index) => (
                      <React.Fragment key={`${result.url}-${index}`}>
                        <ListItem disablePadding>
                          <ListItemButton
                            selected={selectedIndex === index}
                            onClick={() => navigateToResult(result)}
                            className={styles.resultItem}
                            sx={{
                              position: 'relative',
                              backgroundColor: 'transparent',
                              '&.Mui-selected': {
                                backgroundColor: theme.selection,
                                '&::before': {
                                  content: '""',
                                  position: 'absolute',
                                  left: 0,
                                  top: 0,
                                  bottom: 0,
                                  width: '3px',
                                  backgroundColor: 'var(--brand-blue)',
                                },
                              },
                              '&:hover': {
                                backgroundColor: theme.selection,
                              },
                            }}
                          >
                            {/* Top Row: Badge + Title */}
                            <Box className={styles.resultContent}>
                              <Box className={styles.resultHeader}>
                                {/* Badge Type Badge - Only show Admin or Users */}
                                {result.badgeType &&
                                  result.badgeType !== 'none' &&
                                  result.badgeType !== 'both' && (
                                    <Chip
                                      label={result.badgeType.toUpperCase()}
                                      size='small'
                                      sx={{
                                        background: getBadgeColor(
                                          result.badgeType,
                                        ),
                                        color: 'white',
                                        fontWeight: 600,
                                        fontSize: '10px',
                                        height: '20px',
                                        borderRadius: '10px',
                                      }}
                                    />
                                  )}

                                {/* Show both Admin and Users badges if both are true */}
                                {result.badgeType === 'both' && (
                                  <>
                                    <Chip
                                      label='ADMIN'
                                      size='small'
                                      sx={{
                                        background: 'var(--brand-aqua)',
                                        color: 'white',
                                        fontWeight: 600,
                                        fontSize: '10px',
                                        height: '20px',
                                        borderRadius: '10px',
                                      }}
                                    />
                                    <Chip
                                      label='USERS'
                                      size='small'
                                      sx={{
                                        background: 'var(--brand-blue)',
                                        color: 'white',
                                        fontWeight: 600,
                                        fontSize: '10px',
                                        height: '20px',
                                        borderRadius: '10px',
                                      }}
                                    />
                                  </>
                                )}

                                {/* Title */}
                                <Typography
                                  variant='body2'
                                  sx={{
                                    fontWeight: 600,
                                    color: theme.text,
                                    fontSize: '14px',
                                    flex: 1,
                                    minWidth: 0,
                                  }}
                                  noWrap
                                >
                                  {result.title}
                                </Typography>
                              </Box>

                              {/* Content Info */}
                              <Box className={styles.resultMeta}>
                                <Typography
                                  variant='caption'
                                  sx={{
                                    color: theme.text,
                                    opacity: 0.7,
                                    fontSize: '12px',
                                  }}
                                >
                                  {result.breadcrumbs}
                                </Typography>

                                {result.excerpt && (
                                  <Typography
                                    variant='caption'
                                    sx={{
                                      color: theme.text,
                                      opacity: 0.8,
                                      fontSize: '11px',
                                      lineHeight: 1.3,
                                      display: '-webkit-box',
                                      WebkitLineClamp: 2,
                                      WebkitBoxOrient: 'vertical',
                                      overflow: 'hidden',
                                    }}
                                  >
                                    {result.excerpt}
                                  </Typography>
                                )}
                              </Box>
                            </Box>
                          </ListItemButton>
                        </ListItem>
                        {index < results.length - 1 && (
                          <Divider
                            sx={{
                              borderColor: 'var(--brand-grey-300)',
                              opacity: 0.7,
                            }}
                          />
                        )}
                      </React.Fragment>
                    ))}
                  </List>
                </Box>

                {/* Fixed Filter Controls at Bottom */}
                <Box className={styles.fixedFilterSection}>
                  <Divider
                    sx={{ borderColor: 'var(--brand-grey-600)', opacity: 0.8 }}
                  />
                  <Box className={styles.filterSection}>
                    <Typography
                      variant='caption'
                      sx={{
                        color: theme.text,
                        opacity: 0.8,
                        fontSize: '11px',
                        fontWeight: 600,
                        textTransform: 'uppercase',
                        letterSpacing: '0.5px',
                        marginBottom: '8px',
                        display: 'block',
                      }}
                    >
                      Filter Results
                    </Typography>
                    <Box className={styles.filterCheckboxes}>
                      <label className={styles.filterCheckbox}>
                        <input
                          type='checkbox'
                          checked={adminFilter}
                          onChange={e => setAdminFilter(e.target.checked)}
                        />
                        <span>Admin</span>
                      </label>
                      <label className={styles.filterCheckbox}>
                        <input
                          type='checkbox'
                          checked={usersFilter}
                          onChange={e => setUsersFilter(e.target.checked)}
                        />
                        <span>Users</span>
                      </label>
                    </Box>
                  </Box>
                </Box>
              </>
            ) : query.trim() ? (
              <Box className={styles.noResults}>
                <Typography
                  variant='body2'
                  sx={{ color: theme.text, textAlign: 'center' }}
                >
                  No Rita Go results found for "{query}"
                  {(adminFilter || usersFilter) && (
                    <span>
                      {' '}
                      with filter{adminFilter && usersFilter ? 's' : ''}:{' '}
                      {[adminFilter && 'Admin', usersFilter && 'Users']
                        .filter(Boolean)
                        .join(' + ')}
                    </span>
                  )}
                </Typography>
              </Box>
            ) : null}
          </Paper>
        )}
      </div>
    </div>
  )
}

export default RitaGoSearch
